name: Download, Send to Telegram, and Cleanup

on:
  workflow_dispatch:

jobs:
  download-send-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Download Link
        id: read_link
        uses: juliangruber/read-file-action@v1
        with:
          path: link.txt

      - name: Download File
        id: download_file
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: ${{ steps.read_link.outputs.content }}
          target: downloaded_file

      - name: Send File to Telegram
        uses: appleboy/telegram-action@v1.0.0
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          document: downloaded_file
          message: 'Here is the file you requested.'

      - name: Cleanup
        run: rm -rf downloaded_file
