name: Download, Send to Telegram, and Cleanup

on:
  workflow_dispatch:

jobs:
  download-send-cleanup:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Read the download link from a file
      - name: Read Download Link
        id: read_link
        uses: juliangruber/read-file-action@v1
        with:
          path: link.txt

      # Step 3: Download the file using the link
      - name: Download File
        id: download_file
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: ${{ steps.read_link.outputs.content }}  # URL from link.txt
          target: downloaded_file.mkv  # Explicitly set the filename
          auto-match: false
          retry-times: 0

      # Step 4: Send the file to Telegram
      - name: Send File to Telegram
        uses: appleboy/telegram-action@v1.0.0
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Your Telegram bot token
          to: ${{ secrets.TELEGRAM_CHAT_ID }}      # Your Telegram chat ID
          document: downloaded_file.mkv            # Path to the downloaded file
          message: 'Here is the file you requested.'  # Optional message

      # Step 5: Clean up the downloaded file
      - name: Cleanup
        run: rm -rf downloaded_file.mkv
