name: Download, Send to Telegram, and Cleanup

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct download link of the file'
        required: true

jobs:
  download-send-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        id: download_file
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: ${{ github.event.inputs.file_url }}
          target: downloaded_file

      - name: Send File to Telegram
        uses: appleboy/telegram-action@v0.2.0
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          document: downloaded_file
          message: 'Here is the file you requested.'

      - name: Cleanup
        run: rm -rf downloaded_file
