name: Deploy Model to Docker Hub

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vigabots
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Removed the Install Ollama CLI step
      # Removed the Pull the model using Ollama step

      - name: Build Docker image
        run: |
          docker build -t vigabots/qwen2.5:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push vigabots/qwen2.5:latest
