name: Ollama Model to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository (if needed)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vigabots  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from GitHub Secrets

      # Step 4: Install Ollama CLI
      - name: Install Ollama CLI
        run: |
          curl https://ollama.ai/install.sh | sh
          sudo ln -s /usr/local/bin/ollama /usr/bin/ollama

      # Step 5: Pull the Ollama model
      - name: Pull Ollama model
        run: |
          ollama pull huihui_ai/qwen2.5-1m-abliterated:7b

      # Step 6: Copy the model files to a temporary directory
      - name: Copy model files
        run: |
          mkdir -p /tmp/ollama-model/models
          cp -r /usr/share/ollama/.ollama/models/* /tmp/ollama-model/models/

      # Step 7: Create a Dockerfile
      - name: Create Dockerfile
        run: |
          cat <<EOF > /tmp/ollama-model/Dockerfile
          FROM ollama/ollama:latest
          COPY ./models /usr/local/ollama/models
          CMD ["ollama", "run", "huihui_ai/qwen2.5-1m-abliterated:7b"]
          EOF

      # Step 8: Pull the existing Docker image (if it exists)
      - name: Pull existing Docker image (if exists)
        run: |
          docker pull vigabots/qwen2.5:latest || echo "No existing image found, continuing..."

      # Step 9: Build the Docker image
      - name: Build Docker image
        run: |
          cd /tmp/ollama-model
          docker build -t vigabots/qwen2.5:latest .

      # Step 10: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push vigabots/qwen2.5:latest
