name: Upload File to Docker Hub

on:
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  DOCKER_USERNAME: vigabots # Your Docker Hub username
  DOCKER_IMAGE_NAME: my-video-file # Name of the Docker image
  FILE_URL: https://pub-c457a64d90034e34aba3bb1cb1734650.r2.dev/Ramayana.The.Legend.of.Prince.Rama.2025.1080p.Hindi.WEB.DL.5.1.x264.HDHub4u.Tv.mkv # URL of the file to download

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pv (Pipe Viewer)
        run: sudo apt-get install -y pv

      - name: Download file with progress bar
        run: |
          echo -e "\033[35mDownloading file...\033[0m"
          wget -q --show-progress -O video-file.mkv $FILE_URL | pv -petr > /dev/null

      - name: Login to Docker Hub
        run: |
          echo -e "\033[35mLogging into Docker Hub...\033[0m"
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Create Dockerfile
        run: |
          echo -e "\033[35mCreating Dockerfile...\033[0m"
          echo "FROM scratch" > Dockerfile
          echo "COPY video-file.mkv /video-file.mkv" >> Dockerfile

      - name: Build Docker image with progress
        run: |
          echo -e "\033[35mBuilding Docker image...\033[0m"
          docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest . | pv -petr > /dev/null

      - name: Push Docker image to Docker Hub with progress
        run: |
          echo -e "\033[35mPushing Docker image to Docker Hub...\033[0m"
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest | pv -petr > /dev/null

      - name: Logout from Docker Hub
        run: |
          echo -e "\033[35mLogging out from Docker Hub...\033[0m"
          docker logout
