name: Check Runner Specs

on:
  workflow_dispatch:

jobs:
  check-specs:
    runs-on: [self-hosted, 96-core]
    steps:
      - name: Display CPU Information
        run: |
          echo "CPU Info:"
          lscpu

      - name: Display Memory Information
        run: |
          echo "Memory Info:"
          free -h

      - name: Display Disk Usage
        run: |
          echo "Disk Usage:"
          df -h
