name: Speed Test Workflow

on:
  # Trigger the workflow on push to the main branch or manually
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository (optional, if needed)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install speedtest-cli
      - name: Install speedtest-cli
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install speedtest-cli

      # Step 3: Run speedtest-cli and capture the output
      - name: Run Speed Test
        id: speedtest
        run: |
          echo "Running speed test..."
          SPEEDTEST_OUTPUT=$(speedtest-cli --simple)
          echo "$SPEEDTEST_OUTPUT"
          echo "Speedtest results: $SPEEDTEST_OUTPUT" >> $GITHUB_ENV

      # Step 4: Display the results in the GitHub Actions log
      - name: Display Speed Test Results
        run: |
          echo "Speed Test Results:"
          echo "${{ env.Speedtest_results }}"
