name: Upload Ollama Model to Hugging Face

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Ollama Model Name'
        required: true
        default: 'deepseek-r1:1.5b'
      huggingface_repo:
        description: 'Hugging Face Repository Name (Private)'
        required: true
        default: 'vigarepo2/ollama'

jobs:
  upload-model:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          curl https://ollama.ai/install.sh | sh
          pip install huggingface_hub

      # Step 3: Download the Ollama model
      - name: Download Ollama Model
        run: |
          ollama pull ${{ inputs.model_name }}

      # Step 4: Locate the model files
      - name: Locate Model Files
        id: locate_model
        run: |
          MODEL_DIR=~/.ollama/models/${{ inputs.model_name }}
          echo "Model directory: $MODEL_DIR"
          echo "MODEL_DIR=$MODEL_DIR" >> $GITHUB_ENV

      # Step 5: Authenticate with Hugging Face
      - name: Authenticate with Hugging Face
        run: |
          huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}

      # Step 6: Create or Clone the Hugging Face Repository
      - name: Create or Clone Hugging Face Repository
        run: |
          # Check if the repository already exists
          if ! huggingface-cli repo ls | grep -q "${{ inputs.huggingface_repo }}"; then
            huggingface-cli repo create ${{ inputs.huggingface_repo }} --type model
          fi
          # Clone the repository using SSH for authentication
          git clone https://huggingface.co/${{ inputs.huggingface_repo }}

      # Step 7: Upload the model to Hugging Face
      - name: Upload Model to Hugging Face
        run: |
          cp -r ${{ env.MODEL_DIR }}/* ${{ inputs.huggingface_repo }}/
          cd ${{ inputs.huggingface_repo }}
          echo "# Model Card for ${{ inputs.model_name }}" > README.md
          echo "This is the ${{ inputs.model_name }} model downloaded via Ollama and uploaded to Hugging Face." >> README.md
          git add .
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Upload ${{ inputs.model_name }} model"
          git push https://$${{ secrets.HUGGINGFACE_TOKEN }}@huggingface.co/${{ inputs.huggingface_repo }}

      # Step 8: Clean up
      - name: Clean Up
        run: |
          rm -rf ${{ env.MODEL_DIR }}
